android.nonTransitiveRClass=false
android.useAndroidX=true

kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2

org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx12G -Dfile.encoding=UTF-8
org.gradle.parallel=true
# Prevent log spam
org.gradle.warning.mode=none
disable-code-shrink=true
include-dependency-info=false
